Putri branch
Binar-Final-Project/backend pull request #2
Opened 2024-05-24 16:54 UTC by putriNisaRengganis

2024-05-24 17:06 UTC, mirzahafizm commented on request.http
masukkin ke .gitignore aja file ini

2024-05-25 09:21 UTC, putriNisaRengganis commented
Okey, sorry bru buka email

Pada tanggal Sab, 25 Mei 2024 00.06, Mirza Hafiz Muhammad <
***@***.***> menulis:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> On request.http
> <https://github.com/Binar-Final-Project/backend/pull/2#discussion_r1613783846>
> :
>
> masukkin ke .gitignore aja file ini
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Binar-Final-Project/backend/pull/2#pullrequestreview-2077451785>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3RRHHPKPXUY2IMLMICOOILZD5XSZAVCNFSM6AAAAABIH476QCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDANZXGQ2TCNZYGU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-05-25 11:28 UTC, mirzahm14 requested changes

2024-05-25 11:28 UTC, mirzahm14 commented on .env.example
> +DATABASE_URL="postgresql://postgres:root@localhost:5432/tugasAkhir?schema=public"
.env.example gausah diganti mba, ini sebagai template aja, yang diubah di .env local aja

2024-05-25 11:28 UTC, mirzahm14 commented on prisma/schema.prisma
> +  otpExpiry    DateTime?
ini kayanya ga kepake mba, diliat dari UInya ga ada hangusnya gitu

2024-05-25 11:28 UTC, mirzahm14 commented on prisma/schema.prisma
> +  verified     Boolean   @default(false)
sesuaiin sama ERD, jadi "is_verified"

2024-05-25 11:31 UTC, mirzahm14 requested changes

2024-05-25 11:31 UTC, mirzahm14 commented on prisma/schema.prisma
> +model User {
sesuain dengan kesepakatan kemarin dan ERD mba nama modelnya, ganti jadi 'users'

2024-05-26 05:33 UTC, putriNisaRengganis commented
Done!

Pada tanggal Sab, 25 Mei 2024 18.31, Mirza Hafiz Muhammad <
***@***.***> menulis:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In prisma/schema.prisma
> <https://github.com/Binar-Final-Project/backend/pull/2#discussion_r1614597141>
> :
>
> > @@ -12,3 +12,16 @@ datasource db {
>    provider = "postgresql"
>    url      = env("DATABASE_URL")
>  }
> +
> +model User {
>
> sesuain dengan kesepakatan kemarin dan ERD mba nama modelnya, ganti jadi
> 'users'
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Binar-Final-Project/backend/pull/2#pullrequestreview-2078947746>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3RRHHIKS52BX3XNO2CVJM3ZEBZCXAVCNFSM6AAAAABIH476QCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDANZYHE2DONZUGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-05-26 05:34 UTC, putriNisaRengganis commented
coba review lgi mas, aku usahain kalau ada revisi malam ini selesai

Pada tanggal Min, 26 Mei 2024 12.32, Putri Nisa <
***@***.***> menulis:

> Done!
>
> Pada tanggal Sab, 25 Mei 2024 18.31, Mirza Hafiz Muhammad <
> ***@***.***> menulis:
>
>> ***@***.**** requested changes on this pull request.
>> ------------------------------
>>
>> In prisma/schema.prisma
>> <https://github.com/Binar-Final-Project/backend/pull/2#discussion_r1614597141>
>> :
>>
>> > @@ -12,3 +12,16 @@ datasource db {
>>    provider = "postgresql"
>>    url      = env("DATABASE_URL")
>>  }
>> +
>> +model User {
>>
>> sesuain dengan kesepakatan kemarin dan ERD mba nama modelnya, ganti jadi
>> 'users'
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/Binar-Final-Project/backend/pull/2#pullrequestreview-2078947746>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/A3RRHHIKS52BX3XNO2CVJM3ZEBZCXAVCNFSM6AAAAABIH476QCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDANZYHE2DONZUGY>
>> .
>> You are receiving this because you authored the thread.Message ID:
>> ***@***.***>
>>
>

2024-05-26 07:39 UTC, mirzahafizm commented on prisma/schema.prisma
> +  createdAt    DateTime  @default(now())
penamaan 2 kata sesuai kesepakatan kemarin mba, snake_case

2024-05-26 08:21 UTC, putriNisaRengganis commented
mas kalau bisa yg perlu di revisi itu di satuin aja jangan satu satu 😭

Pada tanggal Min, 26 Mei 2024 14.40, Mirza Hafiz Muhammad <
***@***.***> menulis:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In prisma/schema.prisma
> <https://github.com/Binar-Final-Project/backend/pull/2#discussion_r1614639323>
> :
>
> > @@ -12,3 +12,16 @@ datasource db {
>    provider = "postgresql"
>    url      = env("DATABASE_URL")
>  }
> +
> +model User {
> +  id           String    @id @default(cuid())
> +  name         String?
> +  email        String    @unique
> +  phone_number String    @unique
> +  password     String
> +  otp          String?
> +  otpExpiry    DateTime?
> +  verified     Boolean   @default(false)
> +  createdAt    DateTime  @default(now())
>
> penamaan 2 kata sesuai kesepakatan kemarin mba, snake_case
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Binar-Final-Project/backend/pull/2#pullrequestreview-2078962583>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3RRHHMEOLPSNZ3L64BS5EDZEGGVPAVCNFSM6AAAAABIH476QCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDANZYHE3DENJYGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-05-26 10:07 UTC, putriNisaRengganis commented
done mas

Pada tanggal Min, 26 Mei 2024 15.20, Putri Nisa <
***@***.***> menulis:

> mas kalau bisa yg perlu di revisi itu di satuin aja jangan satu satu 😭
>
> Pada tanggal Min, 26 Mei 2024 14.40, Mirza Hafiz Muhammad <
> ***@***.***> menulis:
>
>> ***@***.**** commented on this pull request.
>> ------------------------------
>>
>> In prisma/schema.prisma
>> <https://github.com/Binar-Final-Project/backend/pull/2#discussion_r1614639323>
>> :
>>
>> > @@ -12,3 +12,16 @@ datasource db {
>>    provider = "postgresql"
>>    url      = env("DATABASE_URL")
>>  }
>> +
>> +model User {
>> +  id           String    @id @default(cuid())
>> +  name         String?
>> +  email        String    @unique
>> +  phone_number String    @unique
>> +  password     String
>> +  otp          String?
>> +  otpExpiry    DateTime?
>> +  verified     Boolean   @default(false)
>> +  createdAt    DateTime  @default(now())
>>
>> penamaan 2 kata sesuai kesepakatan kemarin mba, snake_case
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/Binar-Final-Project/backend/pull/2#pullrequestreview-2078962583>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/A3RRHHMEOLPSNZ3L64BS5EDZEGGVPAVCNFSM6AAAAABIH476QCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDANZYHE3DENJYGM>
>> .
>> You are receiving this because you authored the thread.Message ID:
>> ***@***.***>
>>
>

2024-05-27 07:55 UTC, mirzahm14 approved these changes

2024-05-27 07:56 UTC, merged